### PR TITLE
Allow for async init and shutdown functions

### PR DESCRIPTION
**Pull request by jonirap**
Allow for `init` and `shutdown` functions to return promises.

### CODE REVIEW

**Comment by lance** [comment]
@jonirap ping - are you still working on this?

**Comment by jonirap** [comment]
No, I believe it is ready, just didn't know who to add as a reviewer

**Comment by lance** [comment]
> No, I believe it is ready, just didn't know who to add as a reviewer

Okay! Could you please fix the errors in the tests?

**Comment by jonirap** [comment]
> > No, I believe it is ready, just didn't know who to add as a reviewer
> 
> Okay! Could you please fix the errors in the tests?

Fixed :)

**Review by lance — APPROVED** [review]
/lgtm
Thanks for the contribution!

**Pull request merged**
